brew "stow"
brew "git"
brew "neovim"
brew "tmux"
brew "ranger"
brew "k9s"
brew "rclone"
brew "smug"
brew "direnv"
brew "uv"
brew "fnm"
brew "zoxide"
brew "ripgrep"
brew "fzf"
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "lazydocker"
brew "bottom"

cask "nikitabobko/tap/aerospace"
cask "font-inconsolata-nerd-font"
cask "ghostty"
cask "docker"
cask "notion"

